#
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.27
#

Name:       harbour-sailkino

# >> macros
# << macros

%{!?qtc_qmake:%define qtc_qmake %qmake}
%{!?qtc_qmake5:%define qtc_qmake5 %qmake5}
%{!?qtc_make:%define qtc_make make}
%{?qtc_builddir:%define _builddir %qtc_builddir}
Summary:    Finnkino movies.
Version:    0.6
Release:    0
Group:      Qt/Qt
License:    The MIT License (MIT)
URL:        http://example.org/
Source0:    %{name}-%{version}.tar.bz2
Source100:  harbour-sailkino.yaml
Requires:   sailfishsilica-qt5 >= 0.10.9
Requires: nemo-qml-plugin-dbus-qt5
BuildRequires:  pkgconfig(Qt5Quick)
BuildRequires:  pkgconfig(Qt5Qml)
BuildRequires:  pkgconfig(Qt5Core)
BuildRequires:  pkgconfig(sailfishapp) >= 0.0.10

%description
none

%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%qtc_qmake5  \
    VERSION='%{version}-%{release}'

%qtc_make %{?_smp_mflags}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%qmake5_install

# >> install post
# << install post

%files
# >> files
%defattr(0644,root,root,0755)
%attr(0755,-,-) %{_bindir}/%{name}
# << files
/usr/bin
/usr/share/harbour-sailkino
/usr/share/applications
/usr/share/icons/hicolor/86x86/apps
